### ISSUE TITLE
treelib

### ISSUE THREAD

**Issue by jaanos** [zigakodric/Najboljsa_bliznjica#2]
Trenutno imata na repozitoriju celoten Pythonov paket `treelib`. Glede na to, da je ta prosto dostopen v Pythonovih repozitorijih (in seveda tudi na GitHubu), ni potrebe, da imata še eno kopijo na svojem repozitoriju, tako da svetujem, da ga od tam pobrišeta. Če ga bosta uporabljala, to napišita v `README.md`, da bo uporabnik vedel, kaj potrebuje, da lahko poganja vajin program.

V primerih, ko je koda odvisna od nestandardnih različic knjižnic (npr. starejše različice oz. različice z lastnimi ali še nesprejetimi popravki), git omogoča ustvarjanje [podmodulov](https://git-scm.com/book/en/v2/Git-Tools-Submodules), ki kažejo na točno določen commit v drugem repozitoriju. Mislim sicer, da tukaj po tem ni potrebe.

**Comment by zigakodric** [comment]
Odločila sva se, da spremeniva najin repozitorij. Delala bova raje na cocalc, ker je lažje generirati podatke za najin projekt. Lokacija novega repozitorija je https://cocalc.com/projects/e4c7563b-3fff-485b-8ac3-242b5731950e/files/?session=default (popravljeno tudi na wiki-ju za projekte). Prosil bi Vas še, če lahko pogledate ali funkcija casovna_zahtevnost() deluje pravilno. Issue pa zapiram :). Lp

**Comment by jaanos** [comment]
Svetujem, da vseeno obdržita repozitorij na GitHubu, saj bo tako komunikacija enostavnejša - tukaj imamo issueje, lahko se sklicujemo na kodo itd. Je pa res, da bo potrebno ročno poskrbeti za prenos datotek med CoCalcom in GitHubom.

Za projekt na CoCalcu me bosta morala pooblastiti - v zgornji vrstici klikneta na *Settings*, nato pa me pod *Add people to project* najdeta pod fakultetnim e-naslovom.

**Comment by jaanos** [comment]
Svetujem še, da za to vprašanje (in morebitna nadaljnja) naredita kar nov issue - za tega pa kar poskrbita, da ne bo na repozitoriju odvečnih datotek.
