### ISSUE TITLE
casovna_zahtevnost

### ISSUE THREAD

**Issue by katykro** [zigakodric/Najboljsa_bliznjica#3]
Zanima naju, če lahko pogledate ali funkcija casovna_zahtevnost() deluje pravilno. Lp

**Comment by jaanos** [comment]
Načeloma izgleda funkcija v redu (nisem preverjal funkcij, ki jih kliče) - svetoval bi le, da se sama izbira funkcije ne vključi v izmerjen čas:
```sage
def casovna_zahtevnost(n,m,stevilo_bliznjic):
    import time
    funkcija = [bliznjica, dve_bliznjici1, dve_bliznjici2][stevilo_bliznjic-1]
    start = time.time()
    for i in xrange(m):
        funkcija(graphs.RandomTree(n).to_dictionary())
    konec = time.time()
    return(konec-start)
```

**Comment by zigakodric** [comment]
Najlepša hvala. Pojavilo se nama je novo vprašanje. V najini kodi iščeva samo razdalje iz izhodiščne točke do ostalih točk:
```python
def dolzine(graph):
    s = []
    k = list(graph.keys())
    for i in range(1,len(k)):
        s.append(len(bfs_najkrajsa_pot(graph, k[0],k[i]))-1)
    return(sum(s)/(len(k)-1))
```

Algoritem nama zato vedno vrne najboljšo bližnjico glede na izhodišče. Zanima naju ali morava izračunati število povezav glede na vse točke, torej na način:
```python
def dolzine(graph):
    s = []
    k = list(graph.keys())
    for j in range(0,len(k))
        for i in range(0,len(k)):
            if i !=j :
                s.append(len(bfs_najkrajsa_pot(graph, k[j],k[i]))-1)
    return(sum(s)/(len(k)-1))
```

**Comment by jaanos** [comment]
Mišljeno je, da gledata povprečno razdaljo med vsemi točkami v grafu, torej ne samo od korena drevesa. Če delata s Sageovimi grafi, jo lahko dobita enostavno z metodo `average_distance` (kar bo tudi najbrž bolj učinkovito kot izvajanje BFS za vsak par vozlišč).
